### ISSUE TITLE
Beehoo damage is higher when his s2 is +0 instead of +7

### ISSUE THREAD

**Issue by DyalanStamp** [tyopoyt/epic7-damage-calc#133]
Tried using the beehoo calculation but found that, the chart shows more dmg when beehoo's s2 is at +0 instead of +7, have attached screenshots.

beehoo s2 at +7:
![image](https://github.com/tyopoyt/epic7-damage-calc/assets/55474508/7a0574d2-0ca7-449a-ae69-d1f7a531e8b5)

beehoo s2 at +0:
![image](https://github.com/tyopoyt/epic7-damage-calc/assets/55474508/9fa4ce20-bb31-40be-a17a-78ad32f1d721)

stats used to replicate:
attack: 4100
artifact: none
attack buff
burns to detonate: 3

**Comment by tyopoyt** [comment]
This is correct.  The reason for this is that his passive attack increase is shown in the number that shows up in the stats screen in the game.  So, if your beehoo has 4100 attack with the S2 at plus 0, that means his actual attack subs are much higher than if he had 4100 attack with s2 at +7.  The attack buff only acts on his actual attack, not the attack from his passive, so when +0 the attack buff is having more of an effect than if you had the same attack stat at +7.  It's a little bit convoluted but expected behavior.
